class MsiProductInfo
{
    [Guid]$ProductCode;
    [string]$ProductID;
    [string]$PackageName;
    [string]$ProductName;
    [string]$VersionString;
    [string]$Language;
    [string]$Publisher;
    [string]$State;
    [string]$Transforms;
    [string]$DisplayName;
    [string]$PackageCode;
    [string]$AssignmentType;
    [string]$InstanceType;
    [string]$AuthorizedLUAApp;
    [string]$Version;
    [string]$ProductIcon;
    [string]$InstalledProductName;
    [string]$HelpLink;
    [string]$HelpTelephone;
    [string]$InstallLocation;
    [string]$InstallSource;
    [string]$InstallDate;
    [string]$LocalPackage;
    [string]$URLInfoAbout;
    [string]$URLUpdateInfo;
    [string]$VersionMinor;
    [string]$VersionMajor;
    [string]$RegCompany;
    [string]$RegOwner;
    [string]$Uninstallable;
    [string]$PatchType;
    [string]$LUAEnabled;
    [string]$MoreInfoURL;
    [string]$LastUsedSource;
    [string]$LastUsedType;
    [string]$MediaPackagePath;
    [string]$DiskPrompt
}
